version: '3.8'
services:
  db:
    image: postgres:15
    container_name: repsy_postgres
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: repsy123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
