version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repsy_postgres
    restart: always
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: repsy123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: package-manager-app
    container_name: package-manager
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repsydb
      SPRING_DATASOURCE_USERNAME: repsyuser
      SPRING_DATASOURCE_PASSWORD: repsy123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      STORAGE_STRATEGY: object-storage
      MINIO_URL: http://host.docker.internal:9000
      MINIO_ACCESSKEY: admin
      MINIO_SECRETKEY: 12345678
      MINIO_BUCKET: packages

volumes:
  pgdata:
